---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 3
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: registry.gitlab.com/myartifakt/notes:latest
        envFrom:
        - configMapRef:
            name: rds-conn
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10  
          periodSeconds: 2         
